### ISSUE TITLE
NodeSchool Havana website

### ISSUE THREAD

**Issue by olemis** [nodeschool/havana#10]
Barely minimal website needed . See the [the instructions](https://github.com/nodeschool/organizers#2)

**Comment by phinfonet** [comment]
Anyone is doing that? can i start a setup?

**Comment by olemis** [comment]
I plan to upload something later today .

**Comment by olemis** [comment]
Like I just said I uploaded a version based on NodeSchool Paris home page , translated into Spanish and based on the colors of the Cuban flag and all attributions in place . I plan to do a few more things in the next few days .

@phinfonet I've kept all the files of your previous version in case you still want to convert it to a new style , but please use red , white and blue colors .

**Comment by olemis** [comment]
Oops ! ... /me reopening this issue so as to finish the home page .

**Comment by phinfonet** [comment]
@olemis it was just a initial version... I was yet working on that

**Comment by olemis** [comment]
@phinfonet @elMor3no @robertkowalski @aurium I have enhanced the home page so that it will be trilingual (i.e. Spanish + English + French) . It'd be nice to have both Portuguese and German translations as well , but unfortunately I'm not proficient with those languages .
