### ISSUE TITLE
Include NodeSchool Havana 2016 in main events feed 

### ISSUE THREAD

**Issue by olemis** [nodeschool/havana#11]
I do not see NodeSchool Havana listed in the [global events feed](http://nodeschool.io/events.html) . Should we add it ? How ?

**Comment by robertkowalski** [comment]
we have to fill out https://docs.google.com/forms/d/1vYW-Yw82kt_q7WDgBY6gQqFrg3zuD2rDPXEG-cbq7e4/viewform?usp=form_confirm

i just did that

**Comment by robertkowalski** [comment]
it's on the site! :)
