### ISSUE TITLE
Code of Conduct in spanish

### ISSUE THREAD

**Issue by robertkowalski** [nodeschool/havana#2]
@olemis can you help here?

**Comment by olemis** [comment]
What exactly should I do ? IMHO we should start with something similar to the combination of both the [PyCon CoC](https://github.com/python/pycon-code-of-conduct) and/or the [CubaConf CoC](http://www.cubaconf.org/code-of-conduct/)

What d'u think @robertkowalski ?

**Comment by olemis** [comment]
Or maybe you mean translating another CoC (that I'm not aware of) into Spanish ... ?

**Comment by robertkowalski** [comment]
@olemis for the nodeschool event i took the suggested nodeschool CoC from the organizers wiki and opened a PR: https://github.com/nodeschool/havana/pull/1

we can also use http://www.cubaconf.org/code-of-conduct/ which has the basically similar content

**Comment by olemis** [comment]
I'd rather prefer prefer http://www.cubaconf.org/code-of-conduct/ because it includes an important message in the last paragraphs .

**Comment by robertkowalski** [comment]
we can add the last paragraphs to ours :)

**Comment by robertkowalski** [comment]
wow i just noticed you added a lot of stuff to the current PR (i don't get notified if commits are added on github)

**Comment by olemis** [comment]
Could you please add them paragraphs at the end ?

BTW , I guess you should be notified if you subscribe to follow
repository activity , don't u ?

On 1/17/16, Robert Kowalski notifications@github.com wrote:

> wow i just noticed you added a lot of stuff to the current PR (i don't get
> notified if commits are added on github)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/nodeschool/havana/issues/2#issuecomment-172404761

## 

Regards,

Olemis - @olemislc

Apache™ Bloodhound contributor
http://issues.apache.org/bloodhound
http://blood-hound.net

Brython committer
http://brython.info
http://github.com/brython-dev/brython

Blog ES: http://simelo-es.blogspot.com/
Blog EN: http://simelo-en.blogspot.com/

Featured article:

**Comment by robertkowalski** [comment]
yes, but I don't get emails when people push commits onto a branch.

Do you get mail when I push a commit on a branch?

**Comment by robertkowalski** [comment]
Will do!

**Comment by olemis** [comment]
I see your point now . No , I don't .
