### ISSUE TITLE
Create Vagrant + Virtualbox + Ubuntu sandbox 

### ISSUE THREAD

**Issue by olemis** [nodeschool/havana#7]
Since [working offline is a quite probable situation](https://github.com/nodeschool/havana/issues/5#issuecomment-176991745) , a ready-to-use Vagrant + Virtualbox + Ubuntu box would be very useful to run this initial session . Initial version should include the minimal setup needed to run javascripting , learnyounode and functional workshoppers .

**Comment by olemis** [comment]
Initially I'm assigning this issue to @robertkowalski .

**Comment by robertkowalski** [comment]
the problem with a offline sandbox with virtualbox is that sometimes members do not have virtualization in their cpus and the boxes will not boot up
