### ISSUE TITLE
NodeSchool Havana logo

### ISSUE THREAD

**Issue by olemis** [nodeschool/havana#8]
In the next few days I plan to propose a few logos we should use as the visual identity of forthcoming NodeSchool Havana 2016 .

**Comment by olemis** [comment]
Others may add their own proposals as well .
@robertkowalski , have you made any progress on the web site ? If you share the code I can help you build it . Once we choose a logo then we can include it as well .

**Comment by robertkowalski** [comment]
@olemis sadly not, i was travelling the last weeks :( I wanted to keep the website very minimal (just basic markup, almost no fancy CSS) as I don't have much time these days. 

Feel free to take over the task, I don't want to block you.

**Comment by olemis** [comment]
Ok , I created #10 to track web site dev progress ... and of course we'll need to include a logo in there .

**Comment by olemis** [comment]
I have added [three](https://github.com/nodeschool/havana/blob/gh-pages/img/logo.1.svg) [candidate](https://github.com/nodeschool/havana/blob/gh-pages/img/logo.2.svg) [logos](https://github.com/nodeschool/havana/blob/gh-pages/img/logo.3.svg) each one including the silhouette of Alma Mater , a symbol of University of Havana . Feedback is welcome . 

p.s. I'm of the opinion that the letters at the top of [logo.3.png](https://github.com/nodeschool/havana/blob/gh-pages/img/logo.3.svg) are not perfectly aligned . It'd be nice if someone could take a look into this and fix it .

Cc @aurium @phinfonet @elMor3no @robertkowalski

**Comment by robertkowalski** [comment]
wow, great work!

my personal favorite: https://github.com/nodeschool/havana/blob/gh-pages/img/logo.2.svg
